global:
  uid_gid: &uid_gid 1002770000

ui:
  enabled: true
  replicaCount: 1

  rollingUpdate:
    maxUnavailable: 50%
    maxSurge: 50%

  podSecurityContext:
    fsGroup: *uid_gid

  securityContext:
    runAsUser: *uid_gid

  image:
    repository: artifacts.developer.gov.bc.ca/a264-docker/aps-ref-ui
    pullPolicy: Always
    tag: latest

  containerPort: 8000

  imagePullSecrets:
    - name: artifactory-pull

  resources:
    requests:
      cpu: 10m
      memory: 25Mi
    limits:
      cpu: 50m
      memory: 150Mi

api:
  enabled: true
  replicaCount: 1

  rollingUpdate:
    maxUnavailable: 50%
    maxSurge: 50%

  podSecurityContext:
    fsGroup: *uid_gid

  securityContext:
    runAsUser: *uid_gid

  image:
    repository: artifacts.developer.gov.bc.ca/a264-docker/hello-py-api
    pullPolicy: Always
    tag: latest

  containerPort: 8000

  imagePullSecrets:
    - name: artifactory-pull

  resources:
    requests:
      cpu: 10m
      memory: 65Mi
    limits:
      cpu: 50m
      memory: 150Mi

  env:
    AUDIENCE:
      value: aps-reference-hello-py-api
