global:
  uid_gid: &uid_gid 1002770000

ui:
  enabled: true
  replicaCount: 1
  podSecurityContext:
    fsGroup: *uid_gid

  securityContext:
    runAsUser: *uid_gid

  image:
    repository: artifacts.developer.gov.bc.ca/a264-docker/aps-ref-ui
    pullPolicy: Always
    tag: latest

  containerPort: 8000

  imagePullSecrets:
    - name: artifactory-pull

api:
  enabled: true
  replicaCount: 1
  podSecurityContext:
    fsGroup: *uid_gid

  securityContext:
    runAsUser: *uid_gid

  image:
    repository: artifacts.developer.gov.bc.ca/a264-docker/hello-py-api
    pullPolicy: Always
    tag: latest

  containerPort: 8000

  imagePullSecrets:
    - name: artifactory-pull
